# Generated by Django 4.1.7 on 2023-03-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taifa', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
